# Generated by Django 5.2.16 on 2026-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='achievement_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_enhanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='completeness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='jd_match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='keyword_coverage_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='pii_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_coverage_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='improvementsuggestion',
            name='category',
            field=models.CharField(choices=[('Content', 'Content'), ('Projects', 'Projects'), ('Skills', 'Skills'), ('Experience', 'Experience'), ('Education', 'Education'), ('Impact', 'Impact')], default='Content', max_length=50),
        ),
    ]
