# Generated by Django 5.2.16 on 2026-08-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_readiness_score', models.IntegerField(default=0)),
                ('recommended_career', models.CharField(max_length=255)),
                ('confidence_score', models.IntegerField(default=0)),
                ('overall_feedback', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommended_certifications', models.JSONField(blank=True, default=list)),
                ('recommended_projects', models.JSONField(blank=True, default=list)),
                ('interview_topics', models.JSONField(blank=True, default=list)),
                ('roadmap_json', models.JSONField(blank=True, default=list, help_text='Weekly roadmap details')),
                ('learning_resources_json', models.JSONField(blank=True, default=list, help_text='List of learning resources')),
                ('ats_resume_score', models.IntegerField(default=0)),
                ('resume_suggestions', models.JSONField(blank=True, default=list)),
                ('internship_readiness', models.CharField(default='Not Ready', max_length=100)),
                ('placement_readiness', models.CharField(default='Not Ready', max_length=100)),
                ('thirty_day_plan', models.JSONField(blank=True, default=list)),
                ('ninety_day_plan', models.JSONField(blank=True, default=list)),
                ('motivational_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Career Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
