# Generated by Django on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careeranalysis',
            name='ats_resume_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
