# Generated by Django on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_careeranalysis_has_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='radar_chart_json',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic radar chart categories and topic coverage'),
        ),
    ]
