# Generated by Django 5.2.16 on 2026-09-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_careeranalysis_radar_chart_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='target_company_tier',
            field=models.CharField(choices=[('product', 'Product-Based / High-Growth Tech (e.g. Google, Amazon, Startups)'), ('service', 'Enterprise & IT Services (e.g. TCS, Infosys, Wipro, Accenture)'), ('general', 'General / Balanced Industry Standard')], default='general', help_text='Calibrated hiring benchmark: Product vs Service vs General', max_length=50),
        ),
    ]
