# Generated by Django 5.2.16 on 2026-09-29 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('roadmaps', '0002_topic_skills_taught'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCompetencyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(choices=[('CODING_CHALLENGE', 'Coding Challenge'), ('TECHNICAL_QUIZ', 'Technical Quiz'), ('MOCK_INTERVIEW', 'Mock Interview'), ('BEHAVIORAL_STAR', 'Behavioral STAR')], max_length=30)),
                ('score', models.IntegerField()),
                ('confidence_weight', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Interview Competency Evidence',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question_ids', models.JSONField(default=list, help_text='Ordered list of question IDs selected for this quiz session.')),
                ('proctor_violations_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mockinterviewchat',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='career_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_sessions', to='roadmaps.careerpath'),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='current_phase',
            field=models.CharField(default='INTRODUCTION', max_length=30),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='dimension_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores across technical, problem solving, role relevance, communication, structure'),
        ),
        migrations.AddField(
            model_name='proctorlog',
            name='source',
            field=models.CharField(choices=[('CLIENT_REPORTED', 'Client Reported'), ('SERVER_VERIFIED', 'Server Verified')], default='CLIENT_REPORTED', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='entry_point',
            field=models.CharField(blank=True, default='', help_text='Primary function name to evaluate.', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_test_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of hidden test cases evaluated only on submission.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='memory_limit_mb',
            field=models.IntegerField(default=128, help_text='Memory limit in megabytes.'),
        ),
        migrations.AddField(
            model_name='question',
            name='skills_evaluated',
            field=models.CharField(blank=True, default='', help_text='Comma-separated competencies tested by this question.', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, default='', help_text='Initial starter template code for candidates.'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_ms',
            field=models.IntegerField(default=2000, help_text='Execution time limit in milliseconds.'),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='execution_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='execution_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='memory_used_kb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='passed_tests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='test_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userattemptdetail',
            name='total_tests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proctorlog',
            name='session_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, help_text="List of public test cases: [{'input': '...', 'expected': '...', 'function': '...'}]", null=True),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', 'started_at'], name='interviews__user_id_7703ca_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', 'is_completed'], name='interviews__user_id_81a8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='proctorlog',
            index=models.Index(fields=['session_type', 'session_id'], name='interviews__session_a8ede0_idx'),
        ),
        migrations.AddIndex(
            model_name='proctorlog',
            index=models.Index(fields=['user', 'timestamp'], name='interviews__user_id_10c5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'question_type', 'difficulty'], name='interviews__categor_77b511_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='interviews__questio_345747_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'attempted_at'], name='interviews__user_id_e13083_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['category', 'attempted_at'], name='interviews__categor_2f1492_idx'),
        ),
        migrations.AddField(
            model_name='interviewcompetencyevidence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_session', to='interviews.userattempt'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='interviews.questioncategory'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interviewcompetencyevidence',
            index=models.Index(fields=['user', 'skill_name'], name='interviews__user_id_688758_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewcompetencyevidence',
            index=models.Index(fields=['user', 'created_at'], name='interviews__user_id_b28680_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'is_submitted'], name='interviews__user_id_f2f066_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['session_uuid'], name='interviews__session_31ff2b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'category', 'is_submitted'], name='interviews__user_id_db3e83_idx'),
        ),
    ]
