# Generated by Django 5.2.16 on 2026-07-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
