# Generated by Django 5.2.16 on 2026-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='skills_taught',
            field=models.CharField(blank=True, default='', help_text='Comma-separated skills taught or demonstrated by this topic.', max_length=255),
        ),
    ]
